name: rating_server
description: A lightweight Alfred + SQLite backend server for rating albums.
version: 1.0.0

# Dart SDK 버전 설정
environment:
  sdk: ">=3.0.0 <4.0.0"

# 서버에서 사용하는 패키지들
dependencies:
  alfred: ^1.1.1 # Alfred: 간단한 웹 서버 프레임워크
  sqlite3: ^2.0.0 # SQLite 데이터베이스 (native, fast)
  path: ^1.8.3 # 파일 경로 조작용 유틸리티 (cross-platform)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  mongo_dart: ^0.10.5

# 실행 시 필요한 설정 (선택)
executables:
  rating_server: server.dart

# (선택) 개발용 의존성
dev_dependencies:
  lints: ^3.0.0 # Dart 코드 스타일 및 린트 가이드라인

# (선택) 편의성 스크립트나 CLI 툴 추가 가능
